using Dapper;using JH.QueryStudio.Api.Data;using JH.QueryStudio.Api.Domain;using JH.QueryStudio.Api.DTOs;using JH.QueryStudio.Api.Security;using Microsoft.Data.SqlClient;using Microsoft.Data.Sqlite;
namespace JH.QueryStudio.Api.Services;
public interface IConnectionService{Task<IEnumerable<ConnectionResponse>> ListAsync();Task<ConnectionProfile?> GetAsync(Guid id);Task<ConnectionResponse> SaveAsync(ConnectionUpsertRequest r,Guid? id=null);Task DeleteAsync(Guid id);Task<bool> TestAsync(ConnectionUpsertRequest r,CancellationToken ct);string BuildConnectionString(ConnectionProfile p,string? database=null);}
public sealed class ConnectionService(LocalDatabase db,ICredentialProtector protector):IConnectionService{
 static ConnectionResponse Map(ConnectionProfile p)=>new(p.Id,p.Name,p.Server,p.Port,p.AuthenticationType,p.UserName,p.DefaultDatabase,p.Timeout,p.Encrypt,p.TrustServerCertificate,p.Color,p.Environment,p.IsFavorite,p.LastUsedAt);
 public async Task<IEnumerable<ConnectionResponse>> ListAsync(){await using var c=new SqliteConnection(db.ConnectionString);return (await c.QueryAsync<ConnectionProfile>("select * from Connections order by IsFavorite desc, LastUsedAt desc, Name")).Select(Map);} 
 public async Task<ConnectionProfile?> GetAsync(Guid id){await using var c=new SqliteConnection(db.ConnectionString);return await c.QuerySingleOrDefaultAsync<ConnectionProfile>("select * from Connections where Id=@id",new{id});}
 public async Task<ConnectionResponse> SaveAsync(ConnectionUpsertRequest r,Guid? id=null){var p=new ConnectionProfile(id??Guid.NewGuid(),r.Name,r.Server,r.Port,r.AuthenticationType,r.UserName,string.IsNullOrWhiteSpace(r.Password)?null:protector.Protect(r.Password),r.DefaultDatabase,r.Timeout,r.Encrypt,r.TrustServerCertificate,r.Color,r.Environment,r.IsFavorite,DateTimeOffset.UtcNow,null);await using var c=new SqliteConnection(db.ConnectionString);await c.ExecuteAsync("insert or replace into Connections values(@Id,@Name,@Server,@Port,@AuthenticationType,@UserName,@PasswordCipher,@DefaultDatabase,@Timeout,@Encrypt,@TrustServerCertificate,@Color,@Environment,@IsFavorite,@CreatedAt,@LastUsedAt)",p);return Map(p);} 
 public async Task DeleteAsync(Guid id){await using var c=new SqliteConnection(db.ConnectionString);await c.ExecuteAsync("delete from Connections where Id=@id",new{id});}
 public async Task<bool> TestAsync(ConnectionUpsertRequest r,CancellationToken ct){var p=new ConnectionProfile(Guid.Empty,r.Name,r.Server,r.Port,r.AuthenticationType,r.UserName,string.IsNullOrEmpty(r.Password)?null:protector.Protect(r.Password),r.DefaultDatabase,r.Timeout,r.Encrypt,r.TrustServerCertificate,r.Color,r.Environment,false,DateTimeOffset.UtcNow,null);await using var s=new SqlConnection(BuildConnectionString(p));await s.OpenAsync(ct);return true;}
 public string BuildConnectionString(ConnectionProfile p,string? database=null){var b=new SqlConnectionStringBuilder{DataSource=$"{p.Server},{p.Port}",InitialCatalog=database??p.DefaultDatabase??"master",ConnectTimeout=p.Timeout,Encrypt=p.Encrypt,TrustServerCertificate=p.TrustServerCertificate};if(p.AuthenticationType.Equals("Sql",StringComparison.OrdinalIgnoreCase)){b.UserID=p.UserName;b.Password=p.PasswordCipher is null?"":protector.Unprotect(p.PasswordCipher);}else b.IntegratedSecurity=true;return b.ConnectionString;}
}
